"""Added is_pinned in Notices

Revision ID: b79a3a4ac7ac
Revises: 4321b9efca95
Create Date: 2025-12-18 00:42:12.908598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79a3a4ac7ac'
down_revision: Union[str, Sequence[str], None] = '4321b9efca95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'is_pinned')
    # ### end Alembic commands ###
